package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// AttachHighDensityElasticNetworkInterface invokes the eflo.AttachHighDensityElasticNetworkInterface API synchronously
func (client *Client) AttachHighDensityElasticNetworkInterface(request *AttachHighDensityElasticNetworkInterfaceRequest) (response *AttachHighDensityElasticNetworkInterfaceResponse, err error) {
	response = CreateAttachHighDensityElasticNetworkInterfaceResponse()
	err = client.DoAction(request, response)
	return
}

// AttachHighDensityElasticNetworkInterfaceWithChan invokes the eflo.AttachHighDensityElasticNetworkInterface API asynchronously
func (client *Client) AttachHighDensityElasticNetworkInterfaceWithChan(request *AttachHighDensityElasticNetworkInterfaceRequest) (<-chan *AttachHighDensityElasticNetworkInterfaceResponse, <-chan error) {
	responseChan := make(chan *AttachHighDensityElasticNetworkInterfaceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.AttachHighDensityElasticNetworkInterface(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// AttachHighDensityElasticNetworkInterfaceWithCallback invokes the eflo.AttachHighDensityElasticNetworkInterface API asynchronously
func (client *Client) AttachHighDensityElasticNetworkInterfaceWithCallback(request *AttachHighDensityElasticNetworkInterfaceRequest, callback func(response *AttachHighDensityElasticNetworkInterfaceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *AttachHighDensityElasticNetworkInterfaceResponse
		var err error
		defer close(result)
		response, err = client.AttachHighDensityElasticNetworkInterface(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// AttachHighDensityElasticNetworkInterfaceRequest is the request struct for api AttachHighDensityElasticNetworkInterface
type AttachHighDensityElasticNetworkInterfaceRequest struct {
	*requests.RpcRequest
	HighDensityElasticNetworkInterfaceId string           `position:"Body" name:"HighDensityElasticNetworkInterfaceId"`
	EnableSecurityGroup                  requests.Boolean `position:"Body" name:"EnableSecurityGroup"`
	NodeId                               string           `position:"Body" name:"NodeId"`
}

// AttachHighDensityElasticNetworkInterfaceResponse is the response struct for api AttachHighDensityElasticNetworkInterface
type AttachHighDensityElasticNetworkInterfaceResponse struct {
	*responses.BaseResponse
	Code      int     `json:"Code" xml:"Code"`
	Message   string  `json:"Message" xml:"Message"`
	RequestId string  `json:"RequestId" xml:"RequestId"`
	Content   Content `json:"Content" xml:"Content"`
}

// CreateAttachHighDensityElasticNetworkInterfaceRequest creates a request to invoke AttachHighDensityElasticNetworkInterface API
func CreateAttachHighDensityElasticNetworkInterfaceRequest() (request *AttachHighDensityElasticNetworkInterfaceRequest) {
	request = &AttachHighDensityElasticNetworkInterfaceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "AttachHighDensityElasticNetworkInterface", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateAttachHighDensityElasticNetworkInterfaceResponse creates a response to parse from AttachHighDensityElasticNetworkInterface response
func CreateAttachHighDensityElasticNetworkInterfaceResponse() (response *AttachHighDensityElasticNetworkInterfaceResponse) {
	response = &AttachHighDensityElasticNetworkInterfaceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
