package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// AttachElasticNetworkInterface invokes the eflo.AttachElasticNetworkInterface API synchronously
func (client *Client) AttachElasticNetworkInterface(request *AttachElasticNetworkInterfaceRequest) (response *AttachElasticNetworkInterfaceResponse, err error) {
	response = CreateAttachElasticNetworkInterfaceResponse()
	err = client.DoAction(request, response)
	return
}

// AttachElasticNetworkInterfaceWithChan invokes the eflo.AttachElasticNetworkInterface API asynchronously
func (client *Client) AttachElasticNetworkInterfaceWithChan(request *AttachElasticNetworkInterfaceRequest) (<-chan *AttachElasticNetworkInterfaceResponse, <-chan error) {
	responseChan := make(chan *AttachElasticNetworkInterfaceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.AttachElasticNetworkInterface(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// AttachElasticNetworkInterfaceWithCallback invokes the eflo.AttachElasticNetworkInterface API asynchronously
func (client *Client) AttachElasticNetworkInterfaceWithCallback(request *AttachElasticNetworkInterfaceRequest, callback func(response *AttachElasticNetworkInterfaceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *AttachElasticNetworkInterfaceResponse
		var err error
		defer close(result)
		response, err = client.AttachElasticNetworkInterface(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// AttachElasticNetworkInterfaceRequest is the request struct for api AttachElasticNetworkInterface
type AttachElasticNetworkInterfaceRequest struct {
	*requests.RpcRequest
	NodeId                    string `position:"Body" name:"NodeId"`
	ElasticNetworkInterfaceId string `position:"Body" name:"ElasticNetworkInterfaceId"`
}

// AttachElasticNetworkInterfaceResponse is the response struct for api AttachElasticNetworkInterface
type AttachElasticNetworkInterfaceResponse struct {
	*responses.BaseResponse
	Code               int     `json:"Code" xml:"Code"`
	Message            string  `json:"Message" xml:"Message"`
	RequestId          string  `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string  `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            Content `json:"Content" xml:"Content"`
}

// CreateAttachElasticNetworkInterfaceRequest creates a request to invoke AttachElasticNetworkInterface API
func CreateAttachElasticNetworkInterfaceRequest() (request *AttachElasticNetworkInterfaceRequest) {
	request = &AttachElasticNetworkInterfaceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "AttachElasticNetworkInterface", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateAttachElasticNetworkInterfaceResponse creates a response to parse from AttachElasticNetworkInterface response
func CreateAttachElasticNetworkInterfaceResponse() (response *AttachElasticNetworkInterfaceResponse) {
	response = &AttachElasticNetworkInterfaceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
