package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// CreateHighDensityElasticNetworkInterface invokes the eflo.CreateHighDensityElasticNetworkInterface API synchronously
func (client *Client) CreateHighDensityElasticNetworkInterface(request *CreateHighDensityElasticNetworkInterfaceRequest) (response *CreateHighDensityElasticNetworkInterfaceResponse, err error) {
	response = CreateCreateHighDensityElasticNetworkInterfaceResponse()
	err = client.DoAction(request, response)
	return
}

// CreateHighDensityElasticNetworkInterfaceWithChan invokes the eflo.CreateHighDensityElasticNetworkInterface API asynchronously
func (client *Client) CreateHighDensityElasticNetworkInterfaceWithChan(request *CreateHighDensityElasticNetworkInterfaceRequest) (<-chan *CreateHighDensityElasticNetworkInterfaceResponse, <-chan error) {
	responseChan := make(chan *CreateHighDensityElasticNetworkInterfaceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.CreateHighDensityElasticNetworkInterface(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// CreateHighDensityElasticNetworkInterfaceWithCallback invokes the eflo.CreateHighDensityElasticNetworkInterface API asynchronously
func (client *Client) CreateHighDensityElasticNetworkInterfaceWithCallback(request *CreateHighDensityElasticNetworkInterfaceRequest, callback func(response *CreateHighDensityElasticNetworkInterfaceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *CreateHighDensityElasticNetworkInterfaceResponse
		var err error
		defer close(result)
		response, err = client.CreateHighDensityElasticNetworkInterface(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// CreateHighDensityElasticNetworkInterfaceRequest is the request struct for api CreateHighDensityElasticNetworkInterface
type CreateHighDensityElasticNetworkInterfaceRequest struct {
	*requests.RpcRequest
	Role                                   string                                                          `position:"Body" name:"Role"`
	ClientToken                            string                                                          `position:"Body" name:"ClientToken"`
	SecurityGroupId                        string                                                          `position:"Body" name:"SecurityGroupId"`
	Description                            string                                                          `position:"Body" name:"Description"`
	AssumeRoleProxyChain                   *[]CreateHighDensityElasticNetworkInterfaceAssumeRoleProxyChain `position:"Body" name:"AssumeRoleProxyChain"  type:"Repeated"`
	HighDensityElasticNetworkInterfaceName string                                                          `position:"Body" name:"HighDensityElasticNetworkInterfaceName"`
	NodeId                                 string                                                          `position:"Body" name:"NodeId"`
	EnableJumboFrame                       requests.Boolean                                                `position:"Body" name:"EnableJumboFrame"`
	VSwitchId                              string                                                          `position:"Body" name:"VSwitchId"`
	EniTags                                *[]CreateHighDensityElasticNetworkInterfaceEniTags              `position:"Body" name:"EniTags"  type:"Repeated"`
	VpcId                                  string                                                          `position:"Body" name:"VpcId"`
	EnableSecurityGroup                    requests.Boolean                                                `position:"Body" name:"EnableSecurityGroup"`
}

// CreateHighDensityElasticNetworkInterfaceAssumeRoleProxyChain is a repeated param struct in CreateHighDensityElasticNetworkInterfaceRequest
type CreateHighDensityElasticNetworkInterfaceAssumeRoleProxyChain struct {
	CloudAccountId  string `name:"CloudAccountId"`
	RoleNameForPlay string `name:"RoleNameForPlay"`
	RoleType        string `name:"RoleType"`
}

// CreateHighDensityElasticNetworkInterfaceEniTags is a repeated param struct in CreateHighDensityElasticNetworkInterfaceRequest
type CreateHighDensityElasticNetworkInterfaceEniTags struct {
	Value string `name:"Value"`
	Key   string `name:"Key"`
}

// CreateHighDensityElasticNetworkInterfaceResponse is the response struct for api CreateHighDensityElasticNetworkInterface
type CreateHighDensityElasticNetworkInterfaceResponse struct {
	*responses.BaseResponse
	Code               int     `json:"Code" xml:"Code"`
	Message            string  `json:"Message" xml:"Message"`
	RequestId          string  `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string  `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            Content `json:"Content" xml:"Content"`
}

// CreateCreateHighDensityElasticNetworkInterfaceRequest creates a request to invoke CreateHighDensityElasticNetworkInterface API
func CreateCreateHighDensityElasticNetworkInterfaceRequest() (request *CreateHighDensityElasticNetworkInterfaceRequest) {
	request = &CreateHighDensityElasticNetworkInterfaceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "CreateHighDensityElasticNetworkInterface", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateCreateHighDensityElasticNetworkInterfaceResponse creates a response to parse from CreateHighDensityElasticNetworkInterface response
func CreateCreateHighDensityElasticNetworkInterfaceResponse() (response *CreateHighDensityElasticNetworkInterfaceResponse) {
	response = &CreateHighDensityElasticNetworkInterfaceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
