package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DetachElasticNetworkInterface invokes the eflo.DetachElasticNetworkInterface API synchronously
func (client *Client) DetachElasticNetworkInterface(request *DetachElasticNetworkInterfaceRequest) (response *DetachElasticNetworkInterfaceResponse, err error) {
	response = CreateDetachElasticNetworkInterfaceResponse()
	err = client.DoAction(request, response)
	return
}

// DetachElasticNetworkInterfaceWithChan invokes the eflo.DetachElasticNetworkInterface API asynchronously
func (client *Client) DetachElasticNetworkInterfaceWithChan(request *DetachElasticNetworkInterfaceRequest) (<-chan *DetachElasticNetworkInterfaceResponse, <-chan error) {
	responseChan := make(chan *DetachElasticNetworkInterfaceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DetachElasticNetworkInterface(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DetachElasticNetworkInterfaceWithCallback invokes the eflo.DetachElasticNetworkInterface API asynchronously
func (client *Client) DetachElasticNetworkInterfaceWithCallback(request *DetachElasticNetworkInterfaceRequest, callback func(response *DetachElasticNetworkInterfaceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DetachElasticNetworkInterfaceResponse
		var err error
		defer close(result)
		response, err = client.DetachElasticNetworkInterface(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DetachElasticNetworkInterfaceRequest is the request struct for api DetachElasticNetworkInterface
type DetachElasticNetworkInterfaceRequest struct {
	*requests.RpcRequest
	NodeId                    string `position:"Body" name:"NodeId"`
	ElasticNetworkInterfaceId string `position:"Body" name:"ElasticNetworkInterfaceId"`
}

// DetachElasticNetworkInterfaceResponse is the response struct for api DetachElasticNetworkInterface
type DetachElasticNetworkInterfaceResponse struct {
	*responses.BaseResponse
	Code               int    `json:"Code" xml:"Code"`
	Message            string `json:"Message" xml:"Message"`
	RequestId          string `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
}

// CreateDetachElasticNetworkInterfaceRequest creates a request to invoke DetachElasticNetworkInterface API
func CreateDetachElasticNetworkInterfaceRequest() (request *DetachElasticNetworkInterfaceRequest) {
	request = &DetachElasticNetworkInterfaceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "DetachElasticNetworkInterface", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateDetachElasticNetworkInterfaceResponse creates a response to parse from DetachElasticNetworkInterface response
func CreateDetachElasticNetworkInterfaceResponse() (response *DetachElasticNetworkInterfaceResponse) {
	response = &DetachElasticNetworkInterfaceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
