package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DetachHighDensityElasticNetworkInterface invokes the eflo.DetachHighDensityElasticNetworkInterface API synchronously
func (client *Client) DetachHighDensityElasticNetworkInterface(request *DetachHighDensityElasticNetworkInterfaceRequest) (response *DetachHighDensityElasticNetworkInterfaceResponse, err error) {
	response = CreateDetachHighDensityElasticNetworkInterfaceResponse()
	err = client.DoAction(request, response)
	return
}

// DetachHighDensityElasticNetworkInterfaceWithChan invokes the eflo.DetachHighDensityElasticNetworkInterface API asynchronously
func (client *Client) DetachHighDensityElasticNetworkInterfaceWithChan(request *DetachHighDensityElasticNetworkInterfaceRequest) (<-chan *DetachHighDensityElasticNetworkInterfaceResponse, <-chan error) {
	responseChan := make(chan *DetachHighDensityElasticNetworkInterfaceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DetachHighDensityElasticNetworkInterface(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DetachHighDensityElasticNetworkInterfaceWithCallback invokes the eflo.DetachHighDensityElasticNetworkInterface API asynchronously
func (client *Client) DetachHighDensityElasticNetworkInterfaceWithCallback(request *DetachHighDensityElasticNetworkInterfaceRequest, callback func(response *DetachHighDensityElasticNetworkInterfaceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DetachHighDensityElasticNetworkInterfaceResponse
		var err error
		defer close(result)
		response, err = client.DetachHighDensityElasticNetworkInterface(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DetachHighDensityElasticNetworkInterfaceRequest is the request struct for api DetachHighDensityElasticNetworkInterface
type DetachHighDensityElasticNetworkInterfaceRequest struct {
	*requests.RpcRequest
	HighDensityElasticNetworkInterfaceId string `position:"Body" name:"HighDensityElasticNetworkInterfaceId"`
	NodeId                               string `position:"Body" name:"NodeId"`
}

// DetachHighDensityElasticNetworkInterfaceResponse is the response struct for api DetachHighDensityElasticNetworkInterface
type DetachHighDensityElasticNetworkInterfaceResponse struct {
	*responses.BaseResponse
	Code      int     `json:"Code" xml:"Code"`
	Message   string  `json:"Message" xml:"Message"`
	RequestId string  `json:"RequestId" xml:"RequestId"`
	Content   Content `json:"Content" xml:"Content"`
}

// CreateDetachHighDensityElasticNetworkInterfaceRequest creates a request to invoke DetachHighDensityElasticNetworkInterface API
func CreateDetachHighDensityElasticNetworkInterfaceRequest() (request *DetachHighDensityElasticNetworkInterfaceRequest) {
	request = &DetachHighDensityElasticNetworkInterfaceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "DetachHighDensityElasticNetworkInterface", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateDetachHighDensityElasticNetworkInterfaceResponse creates a response to parse from DetachHighDensityElasticNetworkInterface response
func CreateDetachHighDensityElasticNetworkInterfaceResponse() (response *DetachHighDensityElasticNetworkInterfaceResponse) {
	response = &DetachHighDensityElasticNetworkInterfaceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
