package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ExtendCluster invokes the eflo.ExtendCluster API synchronously
func (client *Client) ExtendCluster(request *ExtendClusterRequest) (response *ExtendClusterResponse, err error) {
	response = CreateExtendClusterResponse()
	err = client.DoAction(request, response)
	return
}

// ExtendClusterWithChan invokes the eflo.ExtendCluster API asynchronously
func (client *Client) ExtendClusterWithChan(request *ExtendClusterRequest) (<-chan *ExtendClusterResponse, <-chan error) {
	responseChan := make(chan *ExtendClusterResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.ExtendCluster(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// ExtendClusterWithCallback invokes the eflo.ExtendCluster API asynchronously
func (client *Client) ExtendClusterWithCallback(request *ExtendClusterRequest, callback func(response *ExtendClusterResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *ExtendClusterResponse
		var err error
		defer close(result)
		response, err = client.ExtendCluster(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// ExtendClusterRequest is the request struct for api ExtendCluster
type ExtendClusterRequest struct {
	*requests.RpcRequest
	NodeGroups            *[]ExtendClusterNodeGroups         `position:"Body" name:"NodeGroups"  type:"Json"`
	VpdSubnets            *[]string                          `position:"Body" name:"VpdSubnets"  type:"Json"`
	IgnoreFailedNodeTasks requests.Boolean                   `position:"Body" name:"IgnoreFailedNodeTasks"`
	ClusterId             string                             `position:"Body" name:"ClusterId"`
	IpAllocationPolicy    *[]ExtendClusterIpAllocationPolicy `position:"Body" name:"IpAllocationPolicy"  type:"Json"`
}

// ExtendClusterNodeGroups is a repeated param struct in ExtendClusterRequest
type ExtendClusterNodeGroups struct {
	Nodes       *[]ExtendClusterNodeGroupsNodesItem `name:"Nodes" type:"Repeated"`
	NodeGroupId string                              `name:"NodeGroupId"`
}

// ExtendClusterIpAllocationPolicy is a repeated param struct in ExtendClusterRequest
type ExtendClusterIpAllocationPolicy struct {
	BondPolicy        ExtendClusterIpAllocationPolicyBondPolicy               `name:"BondPolicy" type:"Struct"`
	MachineTypePolicy *[]ExtendClusterIpAllocationPolicyMachineTypePolicyItem `name:"MachineTypePolicy" type:"Repeated"`
	NodePolicy        *[]ExtendClusterIpAllocationPolicyNodePolicyItem        `name:"NodePolicy" type:"Repeated"`
}

// ExtendClusterNodeGroupsNodesItem is a repeated param struct in ExtendClusterRequest
type ExtendClusterNodeGroupsNodesItem struct {
	Hostname      string `name:"Hostname"`
	LoginPassword string `name:"LoginPassword"`
	NodeId        string `name:"NodeId"`
}

// ExtendClusterIpAllocationPolicyBondPolicy is a repeated param struct in ExtendClusterRequest
type ExtendClusterIpAllocationPolicyBondPolicy struct {
	BondDefaultSubnet string                                                `name:"BondDefaultSubnet"`
	Bonds             *[]ExtendClusterIpAllocationPolicyBondPolicyBondsItem `name:"Bonds" type:"Repeated"`
}

// ExtendClusterIpAllocationPolicyMachineTypePolicyItem is a repeated param struct in ExtendClusterRequest
type ExtendClusterIpAllocationPolicyMachineTypePolicyItem struct {
	Bonds       *[]ExtendClusterIpAllocationPolicyMachineTypePolicyItemBondsItem `name:"Bonds" type:"Repeated"`
	MachineType string                                                           `name:"MachineType"`
}

// ExtendClusterIpAllocationPolicyNodePolicyItem is a repeated param struct in ExtendClusterRequest
type ExtendClusterIpAllocationPolicyNodePolicyItem struct {
	Bonds  *[]ExtendClusterIpAllocationPolicyNodePolicyItemBondsItem `name:"Bonds" type:"Repeated"`
	NodeId string                                                    `name:"NodeId"`
}

// ExtendClusterIpAllocationPolicyBondPolicyBondsItem is a repeated param struct in ExtendClusterRequest
type ExtendClusterIpAllocationPolicyBondPolicyBondsItem struct {
	Subnet string `name:"Subnet"`
	Name   string `name:"Name"`
}

// ExtendClusterIpAllocationPolicyMachineTypePolicyItemBondsItem is a repeated param struct in ExtendClusterRequest
type ExtendClusterIpAllocationPolicyMachineTypePolicyItemBondsItem struct {
	Subnet string `name:"Subnet"`
	Name   string `name:"Name"`
}

// ExtendClusterIpAllocationPolicyNodePolicyItemBondsItem is a repeated param struct in ExtendClusterRequest
type ExtendClusterIpAllocationPolicyNodePolicyItemBondsItem struct {
	Subnet string `name:"Subnet"`
	Name   string `name:"Name"`
}

// ExtendClusterResponse is the response struct for api ExtendCluster
type ExtendClusterResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
	TaskId    string `json:"TaskId" xml:"TaskId"`
}

// CreateExtendClusterRequest creates a request to invoke ExtendCluster API
func CreateExtendClusterRequest() (request *ExtendClusterRequest) {
	request = &ExtendClusterRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "ExtendCluster", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateExtendClusterResponse creates a response to parse from ExtendCluster response
func CreateExtendClusterResponse() (response *ExtendClusterResponse) {
	response = &ExtendClusterResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
