package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetHighDensityElasticNetworkInterface invokes the eflo.GetHighDensityElasticNetworkInterface API synchronously
func (client *Client) GetHighDensityElasticNetworkInterface(request *GetHighDensityElasticNetworkInterfaceRequest) (response *GetHighDensityElasticNetworkInterfaceResponse, err error) {
	response = CreateGetHighDensityElasticNetworkInterfaceResponse()
	err = client.DoAction(request, response)
	return
}

// GetHighDensityElasticNetworkInterfaceWithChan invokes the eflo.GetHighDensityElasticNetworkInterface API asynchronously
func (client *Client) GetHighDensityElasticNetworkInterfaceWithChan(request *GetHighDensityElasticNetworkInterfaceRequest) (<-chan *GetHighDensityElasticNetworkInterfaceResponse, <-chan error) {
	responseChan := make(chan *GetHighDensityElasticNetworkInterfaceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.GetHighDensityElasticNetworkInterface(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// GetHighDensityElasticNetworkInterfaceWithCallback invokes the eflo.GetHighDensityElasticNetworkInterface API asynchronously
func (client *Client) GetHighDensityElasticNetworkInterfaceWithCallback(request *GetHighDensityElasticNetworkInterfaceRequest, callback func(response *GetHighDensityElasticNetworkInterfaceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *GetHighDensityElasticNetworkInterfaceResponse
		var err error
		defer close(result)
		response, err = client.GetHighDensityElasticNetworkInterface(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// GetHighDensityElasticNetworkInterfaceRequest is the request struct for api GetHighDensityElasticNetworkInterface
type GetHighDensityElasticNetworkInterfaceRequest struct {
	*requests.RpcRequest
	HighDensityElasticNetworkInterfaceId string `position:"Body" name:"HighDensityElasticNetworkInterfaceId"`
}

// GetHighDensityElasticNetworkInterfaceResponse is the response struct for api GetHighDensityElasticNetworkInterface
type GetHighDensityElasticNetworkInterfaceResponse struct {
	*responses.BaseResponse
	Code               int                                            `json:"Code" xml:"Code"`
	Message            string                                         `json:"Message" xml:"Message"`
	RequestId          string                                         `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string                                         `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            ContentInGetHighDensityElasticNetworkInterface `json:"Content" xml:"Content"`
}

// CreateGetHighDensityElasticNetworkInterfaceRequest creates a request to invoke GetHighDensityElasticNetworkInterface API
func CreateGetHighDensityElasticNetworkInterfaceRequest() (request *GetHighDensityElasticNetworkInterfaceRequest) {
	request = &GetHighDensityElasticNetworkInterfaceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "GetHighDensityElasticNetworkInterface", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateGetHighDensityElasticNetworkInterfaceResponse creates a response to parse from GetHighDensityElasticNetworkInterface response
func CreateGetHighDensityElasticNetworkInterfaceResponse() (response *GetHighDensityElasticNetworkInterfaceResponse) {
	response = &GetHighDensityElasticNetworkInterfaceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
