package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetNetworkInfo invokes the eflo.GetNetworkInfo API synchronously
func (client *Client) GetNetworkInfo(request *GetNetworkInfoRequest) (response *GetNetworkInfoResponse, err error) {
	response = CreateGetNetworkInfoResponse()
	err = client.DoAction(request, response)
	return
}

// GetNetworkInfoWithChan invokes the eflo.GetNetworkInfo API asynchronously
func (client *Client) GetNetworkInfoWithChan(request *GetNetworkInfoRequest) (<-chan *GetNetworkInfoResponse, <-chan error) {
	responseChan := make(chan *GetNetworkInfoResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.GetNetworkInfo(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// GetNetworkInfoWithCallback invokes the eflo.GetNetworkInfo API asynchronously
func (client *Client) GetNetworkInfoWithCallback(request *GetNetworkInfoRequest, callback func(response *GetNetworkInfoResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *GetNetworkInfoResponse
		var err error
		defer close(result)
		response, err = client.GetNetworkInfo(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// GetNetworkInfoRequest is the request struct for api GetNetworkInfo
type GetNetworkInfoRequest struct {
	*requests.RpcRequest
	InstanceId string `position:"Body" name:"InstanceId"`
	NodeId     string `position:"Body" name:"NodeId"`
}

// GetNetworkInfoResponse is the response struct for api GetNetworkInfo
type GetNetworkInfoResponse struct {
	*responses.BaseResponse
}

// CreateGetNetworkInfoRequest creates a request to invoke GetNetworkInfo API
func CreateGetNetworkInfoRequest() (request *GetNetworkInfoRequest) {
	request = &GetNetworkInfoRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "GetNetworkInfo", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateGetNetworkInfoResponse creates a response to parse from GetNetworkInfo response
func CreateGetNetworkInfoResponse() (response *GetNetworkInfoResponse) {
	response = &GetNetworkInfoResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
