package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetXfuseAgentConfig invokes the eflo.GetXfuseAgentConfig API synchronously
func (client *Client) GetXfuseAgentConfig(request *GetXfuseAgentConfigRequest) (response *GetXfuseAgentConfigResponse, err error) {
	response = CreateGetXfuseAgentConfigResponse()
	err = client.DoAction(request, response)
	return
}

// GetXfuseAgentConfigWithChan invokes the eflo.GetXfuseAgentConfig API asynchronously
func (client *Client) GetXfuseAgentConfigWithChan(request *GetXfuseAgentConfigRequest) (<-chan *GetXfuseAgentConfigResponse, <-chan error) {
	responseChan := make(chan *GetXfuseAgentConfigResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.GetXfuseAgentConfig(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// GetXfuseAgentConfigWithCallback invokes the eflo.GetXfuseAgentConfig API asynchronously
func (client *Client) GetXfuseAgentConfigWithCallback(request *GetXfuseAgentConfigRequest, callback func(response *GetXfuseAgentConfigResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *GetXfuseAgentConfigResponse
		var err error
		defer close(result)
		response, err = client.GetXfuseAgentConfig(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// GetXfuseAgentConfigRequest is the request struct for api GetXfuseAgentConfig
type GetXfuseAgentConfigRequest struct {
	*requests.RpcRequest
	EncryptData string `position:"Query" name:"EncryptData"`
}

// GetXfuseAgentConfigResponse is the response struct for api GetXfuseAgentConfig
type GetXfuseAgentConfigResponse struct {
	*responses.BaseResponse
	RequestId     string `json:"RequestId" xml:"RequestId"`
	EncryptConfig string `json:"EncryptConfig" xml:"EncryptConfig"`
	ErrorMsg      string `json:"ErrorMsg" xml:"ErrorMsg"`
}

// CreateGetXfuseAgentConfigRequest creates a request to invoke GetXfuseAgentConfig API
func CreateGetXfuseAgentConfigRequest() (request *GetXfuseAgentConfigRequest) {
	request = &GetXfuseAgentConfigRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "GetXfuseAgentConfig", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateGetXfuseAgentConfigResponse creates a response to parse from GetXfuseAgentConfig response
func CreateGetXfuseAgentConfigResponse() (response *GetXfuseAgentConfigResponse) {
	response = &GetXfuseAgentConfigResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
