package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetDestinationCidrBlock invokes the eflo.GetDestinationCidrBlock API synchronously
func (client *Client) GetDestinationCidrBlock(request *GetDestinationCidrBlockRequest) (response *GetDestinationCidrBlockResponse, err error) {
	response = CreateGetDestinationCidrBlockResponse()
	err = client.DoAction(request, response)
	return
}

// GetDestinationCidrBlockWithChan invokes the eflo.GetDestinationCidrBlock API asynchronously
func (client *Client) GetDestinationCidrBlockWithChan(request *GetDestinationCidrBlockRequest) (<-chan *GetDestinationCidrBlockResponse, <-chan error) {
	responseChan := make(chan *GetDestinationCidrBlockResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.GetDestinationCidrBlock(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// GetDestinationCidrBlockWithCallback invokes the eflo.GetDestinationCidrBlock API asynchronously
func (client *Client) GetDestinationCidrBlockWithCallback(request *GetDestinationCidrBlockRequest, callback func(response *GetDestinationCidrBlockResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *GetDestinationCidrBlockResponse
		var err error
		defer close(result)
		response, err = client.GetDestinationCidrBlock(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// GetDestinationCidrBlockRequest is the request struct for api GetDestinationCidrBlock
type GetDestinationCidrBlockRequest struct {
	*requests.RpcRequest
	InstanceId string `position:"Body" name:"InstanceId"`
}

// GetDestinationCidrBlockResponse is the response struct for api GetDestinationCidrBlock
type GetDestinationCidrBlockResponse struct {
	*responses.BaseResponse
	Code               int     `json:"Code" xml:"Code"`
	Message            string  `json:"Message" xml:"Message"`
	RequestId          string  `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string  `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            Content `json:"Content" xml:"Content"`
}

// CreateGetDestinationCidrBlockRequest creates a request to invoke GetDestinationCidrBlock API
func CreateGetDestinationCidrBlockRequest() (request *GetDestinationCidrBlockRequest) {
	request = &GetDestinationCidrBlockRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "GetDestinationCidrBlock", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateGetDestinationCidrBlockResponse creates a response to parse from GetDestinationCidrBlock response
func CreateGetDestinationCidrBlockResponse() (response *GetDestinationCidrBlockResponse) {
	response = &GetDestinationCidrBlockResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
