package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ListProbeInfos invokes the eflo.ListProbeInfos API synchronously
func (client *Client) ListProbeInfos(request *ListProbeInfosRequest) (response *ListProbeInfosResponse, err error) {
	response = CreateListProbeInfosResponse()
	err = client.DoAction(request, response)
	return
}

// ListProbeInfosWithChan invokes the eflo.ListProbeInfos API asynchronously
func (client *Client) ListProbeInfosWithChan(request *ListProbeInfosRequest) (<-chan *ListProbeInfosResponse, <-chan error) {
	responseChan := make(chan *ListProbeInfosResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.ListProbeInfos(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// ListProbeInfosWithCallback invokes the eflo.ListProbeInfos API asynchronously
func (client *Client) ListProbeInfosWithCallback(request *ListProbeInfosRequest, callback func(response *ListProbeInfosResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *ListProbeInfosResponse
		var err error
		defer close(result)
		response, err = client.ListProbeInfos(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// ListProbeInfosRequest is the request struct for api ListProbeInfos
type ListProbeInfosRequest struct {
	*requests.RpcRequest
	LniIp  string `position:"Body" name:"LniIp"`
	NodeId string `position:"Body" name:"NodeId"`
}

// ListProbeInfosResponse is the response struct for api ListProbeInfos
type ListProbeInfosResponse struct {
	*responses.BaseResponse
	Code               int           `json:"Code" xml:"Code"`
	Message            string        `json:"Message" xml:"Message"`
	RequestId          string        `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string        `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            []ContentItem `json:"Content" xml:"Content"`
}

// CreateListProbeInfosRequest creates a request to invoke ListProbeInfos API
func CreateListProbeInfosRequest() (request *ListProbeInfosRequest) {
	request = &ListProbeInfosRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "ListProbeInfos", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateListProbeInfosResponse creates a response to parse from ListProbeInfos response
func CreateListProbeInfosResponse() (response *ListProbeInfosResponse) {
	response = &ListProbeInfosResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
