package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ListHighDensityElasticNetworkInterfaces invokes the eflo.ListHighDensityElasticNetworkInterfaces API synchronously
func (client *Client) ListHighDensityElasticNetworkInterfaces(request *ListHighDensityElasticNetworkInterfacesRequest) (response *ListHighDensityElasticNetworkInterfacesResponse, err error) {
	response = CreateListHighDensityElasticNetworkInterfacesResponse()
	err = client.DoAction(request, response)
	return
}

// ListHighDensityElasticNetworkInterfacesWithChan invokes the eflo.ListHighDensityElasticNetworkInterfaces API asynchronously
func (client *Client) ListHighDensityElasticNetworkInterfacesWithChan(request *ListHighDensityElasticNetworkInterfacesRequest) (<-chan *ListHighDensityElasticNetworkInterfacesResponse, <-chan error) {
	responseChan := make(chan *ListHighDensityElasticNetworkInterfacesResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.ListHighDensityElasticNetworkInterfaces(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// ListHighDensityElasticNetworkInterfacesWithCallback invokes the eflo.ListHighDensityElasticNetworkInterfaces API asynchronously
func (client *Client) ListHighDensityElasticNetworkInterfacesWithCallback(request *ListHighDensityElasticNetworkInterfacesRequest, callback func(response *ListHighDensityElasticNetworkInterfacesResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *ListHighDensityElasticNetworkInterfacesResponse
		var err error
		defer close(result)
		response, err = client.ListHighDensityElasticNetworkInterfaces(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// ListHighDensityElasticNetworkInterfacesRequest is the request struct for api ListHighDensityElasticNetworkInterfaces
type ListHighDensityElasticNetworkInterfacesRequest struct {
	*requests.RpcRequest
	HighDensityElasticNetworkInterfaceId string           `position:"Body" name:"HighDensityElasticNetworkInterfaceId"`
	PageNumber                           requests.Integer `position:"Body" name:"PageNumber"`
	PageSize                             requests.Integer `position:"Body" name:"PageSize"`
	NodeId                               string           `position:"Body" name:"NodeId"`
	Ip                                   string           `position:"Body" name:"Ip"`
	VSwitchId                            string           `position:"Body" name:"VSwitchId"`
	VpcId                                string           `position:"Body" name:"VpcId"`
	ZoneId                               string           `position:"Body" name:"ZoneId"`
	Status                               string           `position:"Body" name:"Status"`
}

// ListHighDensityElasticNetworkInterfacesResponse is the response struct for api ListHighDensityElasticNetworkInterfaces
type ListHighDensityElasticNetworkInterfacesResponse struct {
	*responses.BaseResponse
	Code               int     `json:"Code" xml:"Code"`
	Message            string  `json:"Message" xml:"Message"`
	RequestId          string  `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string  `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            Content `json:"Content" xml:"Content"`
}

// CreateListHighDensityElasticNetworkInterfacesRequest creates a request to invoke ListHighDensityElasticNetworkInterfaces API
func CreateListHighDensityElasticNetworkInterfacesRequest() (request *ListHighDensityElasticNetworkInterfacesRequest) {
	request = &ListHighDensityElasticNetworkInterfacesRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "ListHighDensityElasticNetworkInterfaces", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateListHighDensityElasticNetworkInterfacesResponse creates a response to parse from ListHighDensityElasticNetworkInterfaces response
func CreateListHighDensityElasticNetworkInterfacesResponse() (response *ListHighDensityElasticNetworkInterfacesResponse) {
	response = &ListHighDensityElasticNetworkInterfacesResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
