package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ListPingMesh invokes the eflo.ListPingMesh API synchronously
func (client *Client) ListPingMesh(request *ListPingMeshRequest) (response *ListPingMeshResponse, err error) {
	response = CreateListPingMeshResponse()
	err = client.DoAction(request, response)
	return
}

// ListPingMeshWithChan invokes the eflo.ListPingMesh API asynchronously
func (client *Client) ListPingMeshWithChan(request *ListPingMeshRequest) (<-chan *ListPingMeshResponse, <-chan error) {
	responseChan := make(chan *ListPingMeshResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.ListPingMesh(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// ListPingMeshWithCallback invokes the eflo.ListPingMesh API asynchronously
func (client *Client) ListPingMeshWithCallback(request *ListPingMeshRequest, callback func(response *ListPingMeshResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *ListPingMeshResponse
		var err error
		defer close(result)
		response, err = client.ListPingMesh(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// ListPingMeshRequest is the request struct for api ListPingMesh
type ListPingMeshRequest struct {
	*requests.RpcRequest
	AgentVersion string `position:"Body" name:"AgentVersion"`
	ClusterName  string `position:"Body" name:"ClusterName"`
	AuthenID     string `position:"Body" name:"AuthenID"`
	AgentType    string `position:"Body" name:"AgentType"`
	Extra        string `position:"Body" name:"Extra"`
	NodeId       string `position:"Body" name:"NodeId"`
	NodeSn       string `position:"Body" name:"NodeSn"`
	IP           string `position:"Body" name:"IP"`
	ClusterId    string `position:"Body" name:"ClusterId"`
}

// ListPingMeshResponse is the response struct for api ListPingMesh
type ListPingMeshResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
	Message   string `json:"Message" xml:"Message"`
}

// CreateListPingMeshRequest creates a request to invoke ListPingMesh API
func CreateListPingMeshRequest() (request *ListPingMeshRequest) {
	request = &ListPingMeshRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "ListPingMesh", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateListPingMeshResponse creates a response to parse from ListPingMesh response
func CreateListPingMeshResponse() (response *ListPingMeshResponse) {
	response = &ListPingMeshResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
