package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// ContentItem is a nested struct in eflo response
type ContentItem struct {
	LeniSipQuota    int      `json:"LeniSipQuota" xml:"LeniSipQuota"`
	ClusterId       string   `json:"ClusterId" xml:"ClusterId"`
	SecurityGroupId string   `json:"SecurityGroupId" xml:"SecurityGroupId"`
	LeniQuota       int      `json:"LeniQuota" xml:"LeniQuota"`
	EcsIp           string   `json:"EcsIp" xml:"EcsIp"`
	EcsId           string   `json:"EcsId" xml:"EcsId"`
	EniIp           string   `json:"EniIp" xml:"EniIp"`
	HdeniQuota      int      `json:"HdeniQuota" xml:"HdeniQuota"`
	NodeId          string   `json:"NodeId" xml:"NodeId"`
	RegionId        string   `json:"RegionId" xml:"RegionId"`
	LniSipQuota     int      `json:"LniSipQuota" xml:"LniSipQuota"`
	ZoneId          string   `json:"ZoneId" xml:"ZoneId"`
	VccId           string   `json:"VccId" xml:"VccId"`
	EniId           string   `json:"EniId" xml:"EniId"`
	EcsStatus       string   `json:"EcsStatus" xml:"EcsStatus"`
	VpcId           string   `json:"VpcId" xml:"VpcId"`
	Status          string   `json:"Status" xml:"Status"`
	VirtualSwitchId string   `json:"VirtualSwitchId" xml:"VirtualSwitchId"`
	TenantId        string   `json:"TenantId" xml:"TenantId"`
	VSwitches       []string `json:"VSwitches" xml:"VSwitches"`
}
