package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// ContentInGetHighDensityElasticNetworkInterface is a nested struct in eflo response
type ContentInGetHighDensityElasticNetworkInterface struct {
	RegionId                               string              `json:"RegionId" xml:"RegionId"`
	ZoneId                                 string              `json:"ZoneId" xml:"ZoneId"`
	HighDensityElasticNetworkInterfaceId   string              `json:"HighDensityElasticNetworkInterfaceId" xml:"HighDensityElasticNetworkInterfaceId"`
	HighDensityElasticNetworkInterfaceName string              `json:"HighDensityElasticNetworkInterfaceName" xml:"HighDensityElasticNetworkInterfaceName"`
	NodeId                                 string              `json:"NodeId" xml:"NodeId"`
	Status                                 string              `json:"Status" xml:"Status"`
	Ip                                     string              `json:"Ip" xml:"Ip"`
	VpcId                                  string              `json:"VpcId" xml:"VpcId"`
	VSwitchId                              string              `json:"VSwitchId" xml:"VSwitchId"`
	SecurityGroupId                        string              `json:"SecurityGroupId" xml:"SecurityGroupId"`
	Message                                string              `json:"Message" xml:"Message"`
	Mac                                    string              `json:"Mac" xml:"Mac"`
	VfId                                   string              `json:"VfId" xml:"VfId"`
	CreateTime                             string              `json:"CreateTime" xml:"CreateTime"`
	GmtModified                            string              `json:"GmtModified" xml:"GmtModified"`
	Description                            string              `json:"Description" xml:"Description"`
	Gateway                                string              `json:"Gateway" xml:"Gateway"`
	EniId                                  string              `json:"EniId" xml:"EniId"`
	EnableJumboFrame                       bool                `json:"EnableJumboFrame" xml:"EnableJumboFrame"`
	Ipv6Addresses                          []Ipv6Addresse      `json:"Ipv6Addresses" xml:"Ipv6Addresses"`
	PrivateIpAddresses                     []PrivateIpAddresse `json:"PrivateIpAddresses" xml:"PrivateIpAddresses"`
}
