package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// SwitchVccConnection invokes the eflo.SwitchVccConnection API synchronously
func (client *Client) SwitchVccConnection(request *SwitchVccConnectionRequest) (response *SwitchVccConnectionResponse, err error) {
	response = CreateSwitchVccConnectionResponse()
	err = client.DoAction(request, response)
	return
}

// SwitchVccConnectionWithChan invokes the eflo.SwitchVccConnection API asynchronously
func (client *Client) SwitchVccConnectionWithChan(request *SwitchVccConnectionRequest) (<-chan *SwitchVccConnectionResponse, <-chan error) {
	responseChan := make(chan *SwitchVccConnectionResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.SwitchVccConnection(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// SwitchVccConnectionWithCallback invokes the eflo.SwitchVccConnection API asynchronously
func (client *Client) SwitchVccConnectionWithCallback(request *SwitchVccConnectionRequest, callback func(response *SwitchVccConnectionResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *SwitchVccConnectionResponse
		var err error
		defer close(result)
		response, err = client.SwitchVccConnection(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// SwitchVccConnectionRequest is the request struct for api SwitchVccConnection
type SwitchVccConnectionRequest struct {
	*requests.RpcRequest
	CenId          string `position:"Body" name:"CenId"`
	VccId          string `position:"Body" name:"VccId"`
	ConnectionType string `position:"Body" name:"ConnectionType"`
	VSwitchId      string `position:"Body" name:"VSwitchId"`
	VpcId          string `position:"Body" name:"VpcId"`
}

// SwitchVccConnectionResponse is the response struct for api SwitchVccConnection
type SwitchVccConnectionResponse struct {
	*responses.BaseResponse
}

// CreateSwitchVccConnectionRequest creates a request to invoke SwitchVccConnection API
func CreateSwitchVccConnectionRequest() (request *SwitchVccConnectionRequest) {
	request = &SwitchVccConnectionRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "SwitchVccConnection", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateSwitchVccConnectionResponse creates a response to parse from SwitchVccConnection response
func CreateSwitchVccConnectionResponse() (response *SwitchVccConnectionResponse) {
	response = &SwitchVccConnectionResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
