package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// UnassignLeniIpv6Addresses invokes the eflo.UnassignLeniIpv6Addresses API synchronously
func (client *Client) UnassignLeniIpv6Addresses(request *UnassignLeniIpv6AddressesRequest) (response *UnassignLeniIpv6AddressesResponse, err error) {
	response = CreateUnassignLeniIpv6AddressesResponse()
	err = client.DoAction(request, response)
	return
}

// UnassignLeniIpv6AddressesWithChan invokes the eflo.UnassignLeniIpv6Addresses API asynchronously
func (client *Client) UnassignLeniIpv6AddressesWithChan(request *UnassignLeniIpv6AddressesRequest) (<-chan *UnassignLeniIpv6AddressesResponse, <-chan error) {
	responseChan := make(chan *UnassignLeniIpv6AddressesResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.UnassignLeniIpv6Addresses(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// UnassignLeniIpv6AddressesWithCallback invokes the eflo.UnassignLeniIpv6Addresses API asynchronously
func (client *Client) UnassignLeniIpv6AddressesWithCallback(request *UnassignLeniIpv6AddressesRequest, callback func(response *UnassignLeniIpv6AddressesResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *UnassignLeniIpv6AddressesResponse
		var err error
		defer close(result)
		response, err = client.UnassignLeniIpv6Addresses(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// UnassignLeniIpv6AddressesRequest is the request struct for api UnassignLeniIpv6Addresses
type UnassignLeniIpv6AddressesRequest struct {
	*requests.RpcRequest
	ClientToken               string    `position:"Body" name:"ClientToken"`
	Ipv6Addresses             *[]string `position:"Body" name:"Ipv6Addresses"  type:"Repeated"`
	ElasticNetworkInterfaceId string    `position:"Body" name:"ElasticNetworkInterfaceId"`
}

// UnassignLeniIpv6AddressesResponse is the response struct for api UnassignLeniIpv6Addresses
type UnassignLeniIpv6AddressesResponse struct {
	*responses.BaseResponse
	Code               int     `json:"Code" xml:"Code"`
	Message            string  `json:"Message" xml:"Message"`
	RequestId          string  `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string  `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            Content `json:"Content" xml:"Content"`
}

// CreateUnassignLeniIpv6AddressesRequest creates a request to invoke UnassignLeniIpv6Addresses API
func CreateUnassignLeniIpv6AddressesRequest() (request *UnassignLeniIpv6AddressesRequest) {
	request = &UnassignLeniIpv6AddressesRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "UnassignLeniIpv6Addresses", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateUnassignLeniIpv6AddressesResponse creates a response to parse from UnassignLeniIpv6Addresses response
func CreateUnassignLeniIpv6AddressesResponse() (response *UnassignLeniIpv6AddressesResponse) {
	response = &UnassignLeniIpv6AddressesResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
