package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// UnassignHdeniIpv6Addresses invokes the eflo.UnassignHdeniIpv6Addresses API synchronously
func (client *Client) UnassignHdeniIpv6Addresses(request *UnassignHdeniIpv6AddressesRequest) (response *UnassignHdeniIpv6AddressesResponse, err error) {
	response = CreateUnassignHdeniIpv6AddressesResponse()
	err = client.DoAction(request, response)
	return
}

// UnassignHdeniIpv6AddressesWithChan invokes the eflo.UnassignHdeniIpv6Addresses API asynchronously
func (client *Client) UnassignHdeniIpv6AddressesWithChan(request *UnassignHdeniIpv6AddressesRequest) (<-chan *UnassignHdeniIpv6AddressesResponse, <-chan error) {
	responseChan := make(chan *UnassignHdeniIpv6AddressesResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.UnassignHdeniIpv6Addresses(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// UnassignHdeniIpv6AddressesWithCallback invokes the eflo.UnassignHdeniIpv6Addresses API asynchronously
func (client *Client) UnassignHdeniIpv6AddressesWithCallback(request *UnassignHdeniIpv6AddressesRequest, callback func(response *UnassignHdeniIpv6AddressesResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *UnassignHdeniIpv6AddressesResponse
		var err error
		defer close(result)
		response, err = client.UnassignHdeniIpv6Addresses(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// UnassignHdeniIpv6AddressesRequest is the request struct for api UnassignHdeniIpv6Addresses
type UnassignHdeniIpv6AddressesRequest struct {
	*requests.RpcRequest
	ClientToken                          string    `position:"Body" name:"ClientToken"`
	Ipv6Addresses                        *[]string `position:"Body" name:"Ipv6Addresses"  type:"Repeated"`
	HighDensityElasticNetworkInterfaceId string    `position:"Body" name:"HighDensityElasticNetworkInterfaceId"`
}

// UnassignHdeniIpv6AddressesResponse is the response struct for api UnassignHdeniIpv6Addresses
type UnassignHdeniIpv6AddressesResponse struct {
	*responses.BaseResponse
	Code               int     `json:"Code" xml:"Code"`
	Message            string  `json:"Message" xml:"Message"`
	RequestId          string  `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string  `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            Content `json:"Content" xml:"Content"`
}

// CreateUnassignHdeniIpv6AddressesRequest creates a request to invoke UnassignHdeniIpv6Addresses API
func CreateUnassignHdeniIpv6AddressesRequest() (request *UnassignHdeniIpv6AddressesRequest) {
	request = &UnassignHdeniIpv6AddressesRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "UnassignHdeniIpv6Addresses", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateUnassignHdeniIpv6AddressesResponse creates a response to parse from UnassignHdeniIpv6Addresses response
func CreateUnassignHdeniIpv6AddressesResponse() (response *UnassignHdeniIpv6AddressesResponse) {
	response = &UnassignHdeniIpv6AddressesResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
