package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// UpdatePrivateIpAddress invokes the eflo.UpdatePrivateIpAddress API synchronously
func (client *Client) UpdatePrivateIpAddress(request *UpdatePrivateIpAddressRequest) (response *UpdatePrivateIpAddressResponse, err error) {
	response = CreateUpdatePrivateIpAddressResponse()
	err = client.DoAction(request, response)
	return
}

// UpdatePrivateIpAddressWithChan invokes the eflo.UpdatePrivateIpAddress API asynchronously
func (client *Client) UpdatePrivateIpAddressWithChan(request *UpdatePrivateIpAddressRequest) (<-chan *UpdatePrivateIpAddressResponse, <-chan error) {
	responseChan := make(chan *UpdatePrivateIpAddressResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.UpdatePrivateIpAddress(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// UpdatePrivateIpAddressWithCallback invokes the eflo.UpdatePrivateIpAddress API asynchronously
func (client *Client) UpdatePrivateIpAddressWithCallback(request *UpdatePrivateIpAddressRequest, callback func(response *UpdatePrivateIpAddressResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *UpdatePrivateIpAddressResponse
		var err error
		defer close(result)
		response, err = client.UpdatePrivateIpAddress(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// UpdatePrivateIpAddressRequest is the request struct for api UpdatePrivateIpAddress
type UpdatePrivateIpAddressRequest struct {
	*requests.RpcRequest
	ClientToken        string `position:"Body" name:"ClientToken"`
	Description        string `position:"Body" name:"Description"`
	IpName             string `position:"Body" name:"IpName"`
	NetworkInterfaceId string `position:"Body" name:"NetworkInterfaceId"`
}

// UpdatePrivateIpAddressResponse is the response struct for api UpdatePrivateIpAddress
type UpdatePrivateIpAddressResponse struct {
	*responses.BaseResponse
	Code               int     `json:"Code" xml:"Code"`
	Message            string  `json:"Message" xml:"Message"`
	RequestId          string  `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string  `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            Content `json:"Content" xml:"Content"`
}

// CreateUpdatePrivateIpAddressRequest creates a request to invoke UpdatePrivateIpAddress API
func CreateUpdatePrivateIpAddressRequest() (request *UpdatePrivateIpAddressRequest) {
	request = &UpdatePrivateIpAddressRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "UpdatePrivateIpAddress", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateUpdatePrivateIpAddressResponse creates a response to parse from UpdatePrivateIpAddress response
func CreateUpdatePrivateIpAddressResponse() (response *UpdatePrivateIpAddressResponse) {
	response = &UpdatePrivateIpAddressResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
