package eflo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// UpdateHighDensityElasticNetworkInterface invokes the eflo.UpdateHighDensityElasticNetworkInterface API synchronously
func (client *Client) UpdateHighDensityElasticNetworkInterface(request *UpdateHighDensityElasticNetworkInterfaceRequest) (response *UpdateHighDensityElasticNetworkInterfaceResponse, err error) {
	response = CreateUpdateHighDensityElasticNetworkInterfaceResponse()
	err = client.DoAction(request, response)
	return
}

// UpdateHighDensityElasticNetworkInterfaceWithChan invokes the eflo.UpdateHighDensityElasticNetworkInterface API asynchronously
func (client *Client) UpdateHighDensityElasticNetworkInterfaceWithChan(request *UpdateHighDensityElasticNetworkInterfaceRequest) (<-chan *UpdateHighDensityElasticNetworkInterfaceResponse, <-chan error) {
	responseChan := make(chan *UpdateHighDensityElasticNetworkInterfaceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.UpdateHighDensityElasticNetworkInterface(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// UpdateHighDensityElasticNetworkInterfaceWithCallback invokes the eflo.UpdateHighDensityElasticNetworkInterface API asynchronously
func (client *Client) UpdateHighDensityElasticNetworkInterfaceWithCallback(request *UpdateHighDensityElasticNetworkInterfaceRequest, callback func(response *UpdateHighDensityElasticNetworkInterfaceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *UpdateHighDensityElasticNetworkInterfaceResponse
		var err error
		defer close(result)
		response, err = client.UpdateHighDensityElasticNetworkInterface(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// UpdateHighDensityElasticNetworkInterfaceRequest is the request struct for api UpdateHighDensityElasticNetworkInterface
type UpdateHighDensityElasticNetworkInterfaceRequest struct {
	*requests.RpcRequest
	SecurityGroupId                        string `position:"Body" name:"SecurityGroupId"`
	HighDensityElasticNetworkInterfaceId   string `position:"Body" name:"HighDensityElasticNetworkInterfaceId"`
	Description                            string `position:"Body" name:"Description"`
	HighDensityElasticNetworkInterfaceName string `position:"Body" name:"HighDensityElasticNetworkInterfaceName"`
}

// UpdateHighDensityElasticNetworkInterfaceResponse is the response struct for api UpdateHighDensityElasticNetworkInterface
type UpdateHighDensityElasticNetworkInterfaceResponse struct {
	*responses.BaseResponse
	Code               int     `json:"Code" xml:"Code"`
	Message            string  `json:"Message" xml:"Message"`
	RequestId          string  `json:"RequestId" xml:"RequestId"`
	AccessDeniedDetail string  `json:"AccessDeniedDetail" xml:"AccessDeniedDetail"`
	Content            Content `json:"Content" xml:"Content"`
}

// CreateUpdateHighDensityElasticNetworkInterfaceRequest creates a request to invoke UpdateHighDensityElasticNetworkInterface API
func CreateUpdateHighDensityElasticNetworkInterfaceRequest() (request *UpdateHighDensityElasticNetworkInterfaceRequest) {
	request = &UpdateHighDensityElasticNetworkInterfaceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("eflo", "2022-05-30", "UpdateHighDensityElasticNetworkInterface", "eflo", "openAPI")
	request.Method = requests.POST
	return
}

// CreateUpdateHighDensityElasticNetworkInterfaceResponse creates a response to parse from UpdateHighDensityElasticNetworkInterface response
func CreateUpdateHighDensityElasticNetworkInterfaceResponse() (response *UpdateHighDensityElasticNetworkInterfaceResponse) {
	response = &UpdateHighDensityElasticNetworkInterfaceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
